# Generated by Django 5.0.1 on 2024-01-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('idProduto', models.AutoField(primary_key=True, serialize=False)),
                ('nomeProduto', models.CharField(max_length=255)),
                ('descricaoProduto', models.TextField()),
                ('precoProduto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('urlImagem', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
